Naming Issues and minor updates
slavik57/enum-values pull request #13
Opened 2017-08-21 20:52 UTC by sbosell

Fixes for variable naming
Return type of null when value's name not found
Test updates
Spacing

2017-08-21 21:05 UTC, slavik57 requested changes
This time don't close the pull request please. Just add a commit and push to the same branch and the commit will be added to this pull request

2017-08-21 21:05 UTC, slavik57 commented on src/enumValues.test.ts
> +
Add a null test here as well

2017-08-21 21:05 UTC, slavik57 commented on src/enumValues.ts
> +    const all = this.getNamesAndValues(e).filter(pair => { return pair.value == value;} );
change the `{ return pair.value == value;}` to  `pair.value === value`
use the `===` instead of `==` and remove the `{}` and the `return`

2017-08-21 21:05 UTC, slavik57 commented on src/enumValues.d.ts
> +    static getNameFromValue(e: any, l: (number | string)): string;
Seems like you didn't build before committing

2017-08-22 15:28 UTC, sbosell commented
Changes made.

2017-08-22 17:07 UTC, slavik57 approved these changes

2017-08-22 17:08 UTC, merged

2017-08-22 17:08 UTC, slavik57 commented
I will publish the package soon

2017-08-22 17:33 UTC, slavik57 commented
Published, you can update it and use the fruits of your great work!
Thanks again 😄